### PR TITLE
README.md example bug

### PR DESCRIPTION
**Pull request by WillemMe**
This is just a small bug in the upload example, found it when trying to run the example.

### CODE REVIEW

**Comment by Dashron** [comment]
Looks great. Do you mind submitting this through our [CLA](https://developer.vimeo.com/cla) and then we'll get it merged in!

**Comment by erunion** [comment]
Hey @WillemMe, if you still want to send this in, can you sign our CLA (https://developer.vimeo.com/cla)? Thanks!

**Comment by WillemMe** [comment]
I forgot about it, but think I did send it in. With this pulls URL, it is pending for approval. I can send again if needed?

**Comment by erunion** [comment]
Oh that's my bad, I didn't see you in our database.

**Comment by WillemMe** [comment]
it's alright no hard feelings.

**Pull request merged**
